development:
  client_id: 1022605865898-vi3ikq1dah235s71q6prdc2sgdrkkqqr.apps.googleusercontent.com
  client_secret: kfftxqMMgULgbsQ7fWIyTzkj

test:
  client_id: 1022605865898-vi3ikq1dah235s71q6prdc2sgdrkkqqr.apps.googleusercontent.com
  client_secret: kfftxqMMgULgbsQ7fWIyTzkj

production:
  client_id: 1022605865898-vi3ikq1dah235s71q6prdc2sgdrkkqqr.apps.googleusercontent.com
  client_secret: kfftxqMMgULgbsQ7fWIyTzkj